# Generated by Django 3.2.5 on 2023-02-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=50)),
                ('total_class', models.PositiveIntegerField()),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.department')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='t_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.teacher'),
        ),
    ]
