# Generated by Django 3.2.5 on 2023-02-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=50)),
                ('total_class', models.PositiveIntegerField()),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.teacher')),
            ],
        ),
    ]
