# Generated by Django 3.2.5 on 2023-02-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.course')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.teacher')),
            ],
        ),
    ]
